spring.application.name=edge-telemetry-pipeline

server.port=8081

spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/telemetry?reWriteBatchedInserts=true
spring.datasource.username=telemetry
spring.datasource.password=telemetry

mqtt.broker-url=tcp://localhost:1883
mqtt.client-id=edge-telemetry-pipeline-subscriber
mqtt.topic=devices/+/readings

queue.capacity = 50
worker.pool-size=10

window.duration-minutes=1
window.grace-period-seconds=10
management.endpoints.web.exposure.include=health,metrics